/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giao_dien;


import HELPER.AUTH;
import HELPER.DialogHelper;
import HELPER.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author PC
 */
public class GIAODIEN_CHINH extends javax.swing.JFrame {
    int index=0;
    /**
     * Creates new form GIAODIEN_CHINH
     */
    public GIAODIEN_CHINH() {
        initComponents();
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnhoadon = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btntaikhoan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnthongke = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btndangxuat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnsanpham = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnidoimatkhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnithoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnisanpham = new javax.swing.JMenuItem();
        mnikhachhang = new javax.swing.JMenuItem();
        mnihoadon = new javax.swing.JMenuItem();
        mnitaikhoan = new javax.swing.JMenuItem();
        mnitksanpham = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnidoanhthu = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnihuongdan = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        xuathoadon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Info.png"))); // NOI18N
        jLabel1.setText("Hệ Thống Quản Lý Giày");

        lblDongHo.setBackground(java.awt.Color.white);
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Alarm.png"))); // NOI18N
        lblDongHo.setText("10:55 PM");
        lblDongHo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnhoadon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Lists.png"))); // NOI18N
        btnhoadon.setText("Quản Lý Hóa Đơn");
        btnhoadon.setFocusable(false);
        btnhoadon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnhoadon.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnhoadon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhoadonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btntaikhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btntaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Key.png"))); // NOI18N
        btntaikhoan.setText("Quản Lý Tài Khoản");
        btntaikhoan.setFocusable(false);
        btntaikhoan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btntaikhoan.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btntaikhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaikhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntaikhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnthongke.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/update-icon.png"))); // NOI18N
        btnthongke.setText("Quản Lý Thống Kê");
        btnthongke.setFocusable(false);
        btnthongke.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnthongke.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnthongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnthongke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btndangxuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Log out.png"))); // NOI18N
        btndangxuat.setText("Đăng xuất");
        btndangxuat.setFocusable(false);
        btndangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btndangxuat.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btndangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btndangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btndangxuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnsanpham.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Card file.png"))); // NOI18N
        btnsanpham.setText("Quản Lý Sản Phẩm");
        btnsanpham.setFocusable(false);
        btnsanpham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnsanpham.setMargin(new java.awt.Insets(12, 30, 12, 30));
        btnsanpham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsanpham)
                .addContainerGap())
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bradley Hand", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Speaker Nhà Làm");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel2ComponentAdded(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/—Pngtree—a pair of colored girls_4940065.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(512, 512));
        jLabel3.setMinimumSize(new java.awt.Dimension(512, 512));
        jLabel3.setPreferredSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Hệ thống");
        jMenu1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mnidangnhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Right.png"))); // NOI18N
        mnidangnhap.setText("Đăng nhập");
        mnidangnhap.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        jMenu1.add(mnidangnhap);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Log out.png"))); // NOI18N
        mnidangxuat.setText("Đăng xuất");
        mnidangxuat.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnidangxuat);
        jMenu1.add(jSeparator1);

        mnidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Refresh.png"))); // NOI18N
        mnidoimatkhau.setText("Đổi mật khẩu");
        mnidoimatkhau.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnidoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoimatkhauActionPerformed(evt);
            }
        });
        jMenu1.add(mnidoimatkhau);
        jMenu1.add(jSeparator2);

        mnithoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnithoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Stop.png"))); // NOI18N
        mnithoat.setText("Thoát");
        mnithoat.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnithoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnithoatActionPerformed(evt);
            }
        });
        jMenu1.add(mnithoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");
        jMenu2.setMargin(new java.awt.Insets(5, 5, 5, 5));

        mnisanpham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnisanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Card file.png"))); // NOI18N
        mnisanpham.setText("Sản Phẩm");
        mnisanpham.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnisanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisanphamActionPerformed(evt);
            }
        });
        jMenu2.add(mnisanpham);

        mnikhachhang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnikhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/User.png"))); // NOI18N
        mnikhachhang.setText("Khách hàng");
        mnikhachhang.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnikhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikhachhangActionPerformed(evt);
            }
        });
        jMenu2.add(mnikhachhang);

        mnihoadon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnihoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Lists.png"))); // NOI18N
        mnihoadon.setText("Hóa đơn");
        mnihoadon.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnihoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihoadonActionPerformed(evt);
            }
        });
        jMenu2.add(mnihoadon);

        mnitaikhoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnitaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Key.png"))); // NOI18N
        mnitaikhoan.setText("Quản lý tài khoản");
        mnitaikhoan.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnitaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitaikhoanActionPerformed(evt);
            }
        });
        jMenu2.add(mnitaikhoan);

        jMenuBar1.add(jMenu2);

        mnitksanpham.setText("Thống kê");
        mnitksanpham.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnitksanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitksanphamActionPerformed(evt);
            }
        });
        mnitksanpham.add(jSeparator3);

        mnidoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnidoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Price list.png"))); // NOI18N
        mnidoanhthu.setText("Thống kê doanh thu ");
        mnidoanhthu.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnidoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoanhthuActionPerformed(evt);
            }
        });
        mnitksanpham.add(mnidoanhthu);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Numbered list.png"))); // NOI18N
        jMenuItem11.setText("Thống kê sản phẩm");
        jMenuItem11.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mnitksanpham.add(jMenuItem11);
        mnitksanpham.add(jSeparator4);

        jMenuBar1.add(mnitksanpham);

        mnihuongdan.setText("Trợ giúp");
        mnihuongdan.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Search.png"))); // NOI18N
        jMenuItem13.setText("Hướng dẫn sử dụng");
        jMenuItem13.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnihuongdan.add(jMenuItem13);
        mnihuongdan.add(jSeparator5);

        xuathoadon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        xuathoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Search.png"))); // NOI18N
        xuathoadon.setText("Xuất hóa đơn");
        xuathoadon.setMargin(new java.awt.Insets(5, 5, 5, 5));
        xuathoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuathoadonActionPerformed(evt);
            }
        });
        mnihuongdan.add(xuathoadon);

        jMenuBar1.add(mnihuongdan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
        this.openlogin();
        
    }//GEN-LAST:event_mnidangnhapActionPerformed

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
        logoff();
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void mnidoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoimatkhauActionPerformed
        this.opendoimatkhau();
       
    }//GEN-LAST:event_mnidoimatkhauActionPerformed

    private void mnithoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnithoatActionPerformed
        if(DialogHelper.confirm(this,"Bạn muốn kêt thúc ứng dụng?")){
        System.exit(0);
          }
        
    }//GEN-LAST:event_mnithoatActionPerformed

    private void mnisanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisanphamActionPerformed
        this.opensanpham();
        
    }//GEN-LAST:event_mnisanphamActionPerformed

    private void mnikhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikhachhangActionPerformed
        this.openkhachang();
        
    }//GEN-LAST:event_mnikhachhangActionPerformed

    private void mnihoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihoadonActionPerformed
        this.openhoadon();

    }//GEN-LAST:event_mnihoadonActionPerformed

    private void mnitaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitaikhoanActionPerformed
        // TODO add your handling code here:
        openTAIKHOAN();
    }//GEN-LAST:event_mnitaikhoanActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
             logoff();
             System.exit(0);
             
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        this.openthongke();
    }//GEN-LAST:event_btnthongkeActionPerformed

    private void btntaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaikhoanActionPerformed
        this.openTAIKHOAN();
    }//GEN-LAST:event_btntaikhoanActionPerformed

    private void btnhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhoadonActionPerformed
       this.openhoadon();
    }//GEN-LAST:event_btnhoadonActionPerformed

    private void btnsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsanphamActionPerformed
        this.opensanpham();
    }//GEN-LAST:event_btnsanphamActionPerformed

    private void mnidoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoanhthuActionPerformed
        this.openthongke();
    }//GEN-LAST:event_mnidoanhthuActionPerformed

    private void mnitksanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitksanphamActionPerformed
        this.openthongke();
    }//GEN-LAST:event_mnitksanphamActionPerformed

    private void xuathoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuathoadonActionPerformed
        // TODO add your handling code here:
        this.openxuathoadon();
    }//GEN-LAST:event_xuathoadonActionPerformed

    private void jPanel2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIAODIEN_CHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIAODIEN_CHINH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btnhoadon;
    private javax.swing.JButton btnsanpham;
    private javax.swing.JButton btntaikhoan;
    private javax.swing.JButton btnthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidoanhthu;
    private javax.swing.JMenuItem mnidoimatkhau;
    private javax.swing.JMenuItem mnihoadon;
    private javax.swing.JMenu mnihuongdan;
    private javax.swing.JMenuItem mnikhachhang;
    private javax.swing.JMenuItem mnisanpham;
    private javax.swing.JMenuItem mnitaikhoan;
    private javax.swing.JMenuItem mnithoat;
    private javax.swing.JMenu mnitksanpham;
    private javax.swing.JMenuItem xuathoadon;
    // End of variables declaration//GEN-END:variables
private void init() {
    this.setLocationRelativeTo(null);
    this.setIconImage(XImage.getAppIcon());

    new ChaoJDialog(this,true).setVisible(true);//OPEN CHÀO 
    new DangNhap(this,true).setVisible(true);
    new Timer(1000,new ActionListener() {// coder đồng hồ

        @Override
        public void actionPerformed(ActionEvent e) {
            Date now = new Date();
            SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
            String text = formater.format(now);
            lblDongHo.setText(text);
        } 

        
    } ).start();
}
private void openhoadon() {
        new Xuat_hoa_don(this,true).setVisible(true);
    }
private void openkhachang() {
        new QL_KHACHHANG(this,true).setVisible(true);
    }
private void opensanpham() {
        new QL_SANPHAM(this,true).setVisible(true);

}
private void openthongke(){
    
        if(AUTH.isLogin()){
            if(index == 3 && AUTH.isManager()){
                DialogHelper.alert(this,"Bạn không có quyền xem thông tin doanh thu");
            }
            else{
                THONGKE_DT_SP tkwin = new THONGKE_DT_SP(this,true);
                tkwin.setVisible(true);
            
            }
        }
        else{
            DialogHelper.alert(this,"Vui lòng đăng nhập !");
        } 
}
    
private void openxuathoadon() {
        new Xuat_hoa_don(this,true).setVisible(true);
}
private void openlogin() {
        new DangNhap(this,true).setVisible(true);
}
private void opendoimatkhau() {
        new DoiMatKhau(this,true).setVisible(true);
}

private void openTAIKHOAN() {
        new TAIKHOAN (this,true).setVisible(true);
}

    void logoff() {
        XImage.logoff();
        this.openlogin();
    }

}
