/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giao_dien;

import DAO.SanPhamDAO;
import MODEL.SANPHAM;
import HELPER.*;
import MODEL.NGUOIDUNG;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class QL_SANPHAM extends javax.swing.JDialog {

    /**
     * Creates new form QL_SANPHAM
     */
    public QL_SANPHAM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        tabs = new javax.swing.JTabbedPane();
        jPanelCAPNHAT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTHEM = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnlui = new javax.swing.JButton();
        btntoi = new javax.swing.JButton();
        btndau = new javax.swing.JButton();
        btncuoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMASP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGIASP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNGAYNHAP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtXUATXU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtTENSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSOLUONG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHSD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMAND = new javax.swing.JTextField();
        lblHinh = new javax.swing.JLabel();
        jPanelDANHMUC = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDS_SANPHAM = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelCAPNHAT.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Hình mô tả");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N

        btnTHEM.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnTHEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Add.png"))); // NOI18N
        btnTHEM.setText("Thêm");
        btnTHEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHEMActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnmoi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Refresh.png"))); // NOI18N
        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnlui.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnlui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Left.png"))); // NOI18N
        btnlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluiActionPerformed(evt);
            }
        });

        btntoi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btntoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Right.png"))); // NOI18N
        btntoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoiActionPerformed(evt);
            }
        });

        btndau.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btndau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/First.png"))); // NOI18N
        btndau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndauActionPerformed(evt);
            }
        });

        btncuoi.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btncuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Last.png"))); // NOI18N
        btncuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoiActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/update-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTHEM, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btntoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncuoi))
                    .addComponent(btndau)
                    .addComponent(btnlui)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTHEM)
                        .addComponent(btnxoa)
                        .addComponent(btnSua)
                        .addComponent(btnmoi)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Mã sản phẩm:");

        txtMASP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtMASP.setName("Mã chuyên đề"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Giá sản phẩm:");

        txtGIASP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtGIASP.setName("Tên chuyên đề"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Ngày nhập:");

        txtNGAYNHAP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtNGAYNHAP.setName("Thời lượng"); // NOI18N
        txtNGAYNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNGAYNHAPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Xuất xứ:");

        txtXUATXU.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtXUATXU.setName("Học phí"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Mô tả chuyên đề");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        txtMoTa.setName("Mô tả chuyên đề"); // NOI18N
        jScrollPane2.setViewportView(txtMoTa);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Tên sản phẩm:");

        txtTENSP.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtTENSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENSPActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Số lượng:");

        txtSOLUONG.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Hạn sử dụng:");

        txtHSD.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Mã người dùng:");

        txtMAND.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCAPNHATLayout = new javax.swing.GroupLayout(jPanelCAPNHAT);
        jPanelCAPNHAT.setLayout(jPanelCAPNHATLayout);
        jPanelCAPNHATLayout.setHorizontalGroup(
            jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                        .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4)
                                    .addComponent(txtMASP, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGIASP, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNGAYNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtXUATXU, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTENSP, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMAND, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCAPNHATLayout.setVerticalGroup(
            jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelCAPNHATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTENSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8)
                                .addComponent(txtSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)
                                .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMAND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGIASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(11, 11, 11)
                                .addComponent(txtNGAYNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtXUATXU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCAPNHATLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tabs.addTab("Cập Nhật", jPanelCAPNHAT);

        tblDS_SANPHAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sp", "Tên SP", "Giá ", "Số lượng", "Ngày Nhập", "Hạn sử dụng", "Xuất sứ", "Mô tả", "Mã ND ", "Hình "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDS_SANPHAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDS_SANPHAMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDS_SANPHAM);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HINH/Search.png"))); // NOI18N
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDANHMUCLayout = new javax.swing.GroupLayout(jPanelDANHMUC);
        jPanelDANHMUC.setLayout(jPanelDANHMUCLayout);
        jPanelDANHMUCLayout.setHorizontalGroup(
            jPanelDANHMUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDANHMUCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDANHMUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDANHMUCLayout.setVerticalGroup(
            jPanelDANHMUCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDANHMUCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        tabs.addTab("Danh Mục", jPanelDANHMUC);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)), "Quản Lý Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Helvetica Neue", 3, 24), new java.awt.Color(0, 102, 204))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTHEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHEMActionPerformed
        this.insert();
    }//GEN-LAST:event_btnTHEMActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void txtNGAYNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNGAYNHAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNGAYNHAPActionPerformed

    private void txtTENSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTENSPActionPerformed

    private void btndauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndauActionPerformed
       this.first();
       tblDS_SANPHAM.setRowSelectionInterval(this.row, this.row);
    }//GEN-LAST:event_btndauActionPerformed

    private void btncuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoiActionPerformed
        this.last();
        tblDS_SANPHAM.setRowSelectionInterval(this.row, this.row);
    }//GEN-LAST:event_btncuoiActionPerformed

    private void btntoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoiActionPerformed
        this.next();
        tblDS_SANPHAM.setRowSelectionInterval(this.row, this.row);
    }//GEN-LAST:event_btntoiActionPerformed

    private void btnluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluiActionPerformed
        this.prev();
        tblDS_SANPHAM.setRowSelectionInterval(this.row, this.row);
    }//GEN-LAST:event_btnluiActionPerformed

    private void tblDS_SANPHAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDS_SANPHAMMouseClicked
        if(evt.getClickCount() == 2){
            this.row = tblDS_SANPHAM.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblDS_SANPHAMMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        this.chonAnh();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btntimkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QL_SANPHAM dialog = new QL_SANPHAM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTHEM;
    private javax.swing.JButton btncuoi;
    private javax.swing.JButton btndau;
    private javax.swing.JButton btnlui;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btntoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCAPNHAT;
    private javax.swing.JPanel jPanelDANHMUC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDS_SANPHAM;
    private javax.swing.JTextField txtGIASP;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtMAND;
    private javax.swing.JTextField txtMASP;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNGAYNHAP;
    private javax.swing.JTextField txtSOLUONG;
    private javax.swing.JTextField txtTENSP;
    private javax.swing.JTextField txtXUATXU;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
    SanPhamDAO dao = new SanPhamDAO();
    int row;
    private void init() {
        this.setLocationRelativeTo(null);
        this.row = -1;
        this.clearForm();
        this.fillTable();
        this.updateStatus();
    }
    
   private void insert() {
        SANPHAM sp = this.getForm();
       try {
          dao.insert(sp);
            this.fillTable();
            this.clearForm();
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
           DialogHelper.alert(this, "Thêm mới thất bại!");
        }

   }
   
    

    private void update() {
        SANPHAM sp = this.getForm();
        try {
            dao.update(sp);
            this.fillTable();
            this.clearForm();
            DialogHelper.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
    }
    
    private void delete() {
        String masp = txtMASP.getText();
        if(DialogHelper.confirm(this, "bạn có thực sự muốn xóa khách hàng này")){
                try{
                    dao.delete(masp);
                    this.clearForm();
                    DialogHelper.alert(this, "Xóa khách hàng thành công!");
                    this.fillTable();
                }catch(Exception e){
                    e.printStackTrace();
                    DialogHelper.alert(this, "Xóa khách hàng thất bại");
                }
        }
    }
    
    private void clearForm() {
        SANPHAM sp = new SANPHAM();
        this.setForm(sp);
        txtGIASP.setText("");
        txtSOLUONG.setText("");
        txtNGAYNHAP.setText("");
        txtHSD.setText("");
        lblHinh.setIcon(null);
        this.row = -1;
        this.updateStatus();
    }
    
    private void setForm(SANPHAM sp){
        txtMASP.setText(sp.getMASP());
        txtTENSP.setText(sp.getTENSP());
        txtGIASP.setText(String.valueOf(sp.getGIA()));
        txtSOLUONG.setText(String.valueOf(sp.getSOLUONG()));
        txtNGAYNHAP.setText(DateHelper.toString(sp.getNGAYNHAP(), "dd-MM-yyyy"));
        txtHSD.setText(DateHelper.toString(sp.getHANSUDUNG(), "dd-MM-yyyy"));
        txtXUATXU.setText(sp.getXUATXU());
        txtMAND.setText(sp.getMAND());
        txtMoTa.setText(sp.getMOTA());
//        if (sp.getHINH()!= null) {
//            try {
//                lblHinh.setToolTipText(sp.getHINH());
//                lblHinh.setIcon(XImage.readAndResize(lblHinh, sp.getHINH()));
//            } catch (IOException ex) {
//                setDefault();
//                DialogHelper.alert(this, "Lỗi tải hình ảnh");
//            }
//        } else {
//            setDefault();
//        }
        if (sp.getHINH()!= null) {
            try {
                lblHinh.setToolTipText(sp.getHINH());
                lblHinh.setIcon(XImage.readAndResize(lblHinh, sp.getHINH()));
            } catch (IOException ex) {
                setDefault();
                DialogHelper.alert(this, "Lỗi tải hình ảnh");
            }
        } else {
            lblHinh.setToolTipText(null);
        }
        
        
    }
    
    private void setDefault() {
        try {
            lblHinh.setToolTipText(null);
            XImage.setDefaultImage(lblHinh);
        } catch (IOException ex) {
            DialogHelper.alert(this, "Lỗi tải hình ảnh");
        }
    }
    
    private void updateStatus(){
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblDS_SANPHAM.getRowCount() -1);
        // trạng thái form 
        txtMASP.setEditable(!edit);
        btnTHEM.setEnabled(!edit);
        txtTENSP.setEditable(!edit);
        btnSua.setEnabled(edit);
        btnxoa.setEnabled(edit);
        //trạng thái điều hướng
        btndau.setEnabled(edit && !first);
        btnlui.setEnabled(edit && !first);
        btntoi.setEnabled(edit && !last);
        btncuoi.setEnabled(edit && !last);
    }

    private void fillTable() {
//        DefaultTableModel model = (DefaultTableModel) tblDS_SANPHAM.getModel();
//        model.setRowCount(0);
//        try{
//            List<SANPHAM> list = dao.selectAll();
//            for(SANPHAM sp : list){
//                Object[] row = {
//                    sp.getMASP(), sp.getTENSP(), sp.getGIA(), sp.getSOLUONG(), sp.getNGAYNHAP(), sp.getHANSUDUNG(), sp.getXUATXU(), sp.getMOTA(), sp.getMAND(), sp.getHINH()
//                };
//                model.addRow(row);
//            }
//        }catch(Exception e){
//            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
//        }
        
        DefaultTableModel model = (DefaultTableModel) tblDS_SANPHAM.getModel();
        model.setRowCount(0);
        try {
            String keyword = txttimkiem.getText();
            List<SANPHAM> list= dao.selectByKeyword(keyword);
            list.forEach(sp -> {
                Object[] tempRow = {sp.getMASP(), sp.getTENSP(), sp.getGIA(), sp.getSOLUONG(), sp.getNGAYNHAP(), sp.getHANSUDUNG(), sp.getXUATXU(), sp.getMOTA(), sp.getMAND(), sp.getHINH()
                };
                model.addRow(tempRow);
            });
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private SANPHAM getForm() {
        SANPHAM sp = new SANPHAM();
        sp.setMASP(txtMASP.getText());
        sp.setTENSP(txtTENSP.getText());
        sp.setGIA(Double.valueOf(txtGIASP.getText()));
        sp.setSOLUONG(Integer.valueOf(txtSOLUONG.getText()));
        sp.setNGAYNHAP(DateHelper.toDate(txtNGAYNHAP.getText(), "dd-MM-yyyy"));
        sp.setHANSUDUNG(DateHelper.toDate(txtHSD.getText(), "dd-MM-yyyy"));
        sp.setXUATXU(txtXUATXU.getText());
        sp.setMAND(txtMAND.getText());
        sp.setHINH(lblHinh.getToolTipText());
        sp.setMOTA(txtMoTa.getText());
        return sp;
    }
    
    void edit(){
        String masp = (String) tblDS_SANPHAM.getValueAt(this.row, 0);
        SANPHAM sp = dao.selectById(masp);
        this.setForm(sp);
        tabs.setSelectedIndex(0);
        this.updateStatus();
        
    }
    
    void first(){
        this.row = 0;
        this.edit();
    }
    void prev(){
        if(this.row > 0){
            this.row --;
            this.edit();
        }
    }
    void next(){
        if(this.row < tblDS_SANPHAM.getRowCount() - 1){
            this.row ++;
            this.edit();
        }
    }
    void last(){
        this.row = tblDS_SANPHAM.getRowCount() - 1;
        this.edit();
    }
    
    private void chonAnh() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file);
            try {
                lblHinh.setIcon(XImage.readAndResize(lblHinh, file.getName()));
            } catch (IOException ex) {
                DialogHelper.alert(this, "Lỗi tải hình ảnh");
            }
            lblHinh.setToolTipText(file.getName());
        }
    }
    void clear()

    {
         txtGIASP.setText("");
        txtHSD.setText("");
        txtMAND.setText("");
        txtMASP.setText("");
        txtMoTa.setText("");
        txtNGAYNHAP.setText("");
        txtSOLUONG.setText("");
        txtTENSP.setText("");
        txtXUATXU.setText("");
        this.row = -1;
        this.updateStatus();
    
    }
     void search()
    {
        this.fillTable();
        this.clear();
        this.row = -1;
        this.updateStatus();
    }
}
